# This is a basic workflow to help you get started with Actions

name: scrape that web

# Controls when the workflow will run
on:
  workflow_dispatch: #enables to run manually 
  #schedule:
    #- cron: "30 1 * * 1-5"
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  scrape:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: set up environment
        run: | #creates multi-line string
           pip install playwright
           playwright install chromium
           python3 script.py
           ls -a
           git config --global user.email "kalexandrine22@protonmail.com"
           git config --global user.name "kalexandrine22"
           git add . 
           git commit -m "commitin' that screenshot"
           git push origin main
